version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fast_api_default_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - fast_api_default_volume:/var/lib/mysql
    networks:
      - fast_api_network

  api:
    build: .
    container_name: fast_api_app
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env_docker.dev}
    depends_on:
      - mysql
    networks:
      - fast_api_network

networks:
  fast_api_network:
    driver: bridge

volumes:
  fast_api_default_volume:
    name: fast_api_default_volume